#!/bin/bash

# Visual Studio Code :: Package list
pkglist=(
alefragnani.project-manager
ampcpmgp.cognitive-complexity-show
dbaeumer.vscode-eslint
dotdevru.prettier-java
eamodio.gitlens
editorconfig.editorconfig
esbenp.prettier-vscode
firsttris.vscode-jest-runner
foxundermoon.shell-format
github.copilot
github.copilot-chat
gruntfuggly.todo-tree
hbenl.vscode-test-explorer
jundat95.react-native-snippet
lfs.vscode-emacs-unfriendly
llvm-vs-code-extensions.lldb-dap
mathiasfrohlich.kotlin
ms-python.black-formatter
ms-python.debugpy
ms-python.isort
ms-python.python
ms-python.vscode-pylance
ms-python.vscode-python-envs
ms-toolsai.jupyter
ms-toolsai.jupyter-keymap
ms-toolsai.jupyter-renderers
ms-toolsai.vscode-jupyter-cell-tags
ms-toolsai.vscode-jupyter-slideshow
ms-vscode.cmake-tools
ms-vscode.cpptools
ms-vscode.cpptools-extension-pack
ms-vscode.cpptools-themes
ms-vscode.live-server
ms-vscode.test-adapter-converter
mtxr.sqltools
mtxr.sqltools-driver-mysql
orta.vscode-jest
rangav.vscode-thunder-client
redhat.fabric8-analytics
redhat.java
richie5um2.vscode-sort-json
ryanluker.vscode-coverage-gutters
sburg.vscode-javascript-booster
streetsidesoftware.code-spell-checker
swiftlang.swift-vscode
toba.vsfire
twxs.cmake
usernamehw.autolink
vadimcn.vscode-lldb
visualstudioexptteam.intellicode-api-usage-examples
visualstudioexptteam.vscodeintellicode
vscjava.migrate-java-to-azure
vscjava.vscode-gradle
vscjava.vscode-java-debug
vscjava.vscode-java-dependency
vscjava.vscode-java-pack
vscjava.vscode-java-test
vscjava.vscode-java-upgrade
vscjava.vscode-maven
vscodevim.vim
vspacecode.whichkey
wmaurer.change-case
xabikos.jasminesnippets
xabikos.javascriptsnippets
)

for i in ${pkglist[@]}; do
  code --install-extension $i
done
